language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true

cache: cargo

script:
  - cargo build --verbose
  - cargo doc --verbose
  - cargo test --verbose -- --nocapture

notifications:
  email:
    on_success: change
    on_failure: always
